### PR TITLE
Unit integration test

### PR DESCRIPTION
**Pull request by SaneMyburg**
Add tests

### CODE REVIEW

**Review by SabiMantock — CHANGES_REQUESTED** [review]
Hi @SaneMyburg, a job well done! but there are some small issues, when I ran the test out of 64 46 passed but the other 18 failed because of this Error: 
``` 
 Failure/Error: visit shopping_list_path
 Webdrivers::BrowserNotFound:
     Failed to determine Chrome binary location.
```
 I added the image below. 
image

Can you please check if you are having the same issue if yes, we can setup a meet to fix it.

**Comment by SaneMyburg** [comment]
> Hi @SaneMyburg, a job well done! but there are some small issues, when I ran the test out of 64 46 passed but the other 18 failed because of this Error:
> 
> ```
>  Failure/Error: visit shopping_list_path
>  Webdrivers::BrowserNotFound:
>      Failed to determine Chrome binary location.
> ```
> 
> I added the image below. image
> 
> Can you please check if you are having the same issue if yes, we can setup a meet to fix it.

Hey @SabiMantock I've just checked again in another pc,they are all passing. Did you run bundle install as there are some gems are added. If not please do and check again.

**Comment by SabiMantock** [comment]
> > Hi @SaneMyburg, a job well done! but there are some small issues, when I ran the test out of 64 46 passed but the other 18 failed because of this Error:
> > ```
> >  Failure/Error: visit shopping_list_path
> >  Webdrivers::BrowserNotFound:
> >      Failed to determine Chrome binary location.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I added the image below. image
> > Can you please check if you are having the same issue if yes, we can setup a meet to fix it.
> 
> Hey @SabiMantock I've just checked again in another pc,they are all passing. Did you run bundle install as there are some gems are added. If not please do and check again.

i did. well done tho

**Review by SabiMantock — APPROVED** [review]
good job

**Pull request merged**
